---
applications:
  .:
    name: express-seed
    framework:
      name: node
      info:
        mem: 64M
        description: Node.js Application
        exec: 
    infra: eu-aws
    url: ${name}.${target-base}
    mem: 64M
    instances: 1
    services:
      mongodb-43592:
        type: mongodb
    env:
      NODE_ENV: production